### ISSUE TITLE
Remove obsolete comment

### ISSUE THREAD

**Issue by vinipsmaker2** [breese/trial.protocol#11]
There is a `FIXME` comment already fixed: https://github.com/breese/trial.protocol/blob/cadcba33750a5a975791c7e2d27f0262e0f6a018/include/trial/protocol/json/detail/reader.ipp#L262

I mean, I was surprised to see this comment, because on my tests, there was already an exception happening on overflow. Then I went further into implementation and saw implementation: https://github.com/breese/trial.protocol/blob/cadcba33750a5a975791c7e2d27f0262e0f6a018/include/trial/protocol/json/detail/decoder.ipp#L244

**Comment by breese** [comment]
Removed in 15099b31a3859618ef8cbbe378973c741d019e39
