### ISSUE TITLE
Interface scoping via prefix or nested struct?

### ISSUE THREAD

**Issue by breese** [breese/trial.protocol#14]
`dynamic::variable` is a heteregenous data structure that can contain both arrays (`std::vector<T>`) and associated arrays (`std::map<T, U>`). Only the associated arrays have keys, so the iterators dereferences the value. Therefore a special key iterator, which dereferences the key, and associated functions have been added.

We need a way to distinguish between the two in the interface.

The conventional way is to use a prefix. For example:
```
variable::key_iterator it = object.key_begin();
variable::key_iterator it2 = object.key_find("key");
```
I have experimented with an alternative (emulating inner classes) that uses C++ constructs (scoped resolution operator and dot operator) instead of prefixes. This gives the following interface:
```
variable::key::iterator it = object.key.begin();
variable::key::iterator it2 = object.key.find("key");
```
While I find this to be a nicely scoped interface, the price is that each `variable` object will contain an extra pointer (the nested key struct has a pointer to its parent class.)

Is this an acceptable price or should I revert to prefixes?

**Comment by breese** [comment]
The solution I am moving towards is to (i) use prefix for the iterator (and `begin`/`end`), and (ii) change the other key-related member functions into free-standing algorithms:
```
  variable::key_iterator it = object.key_begin();
  variable::key_iterator it2 = key::find(object, "key");
```
That way we can also keep the `variable` API more lean.

**Comment by breese** [comment]
The last suggested solution was chosen.

**Comment by vinipsmaker** [comment]
Sorry about the late response. I was on vacation.

> The last suggested solution was chosen.

I'm fine with it.

If I was going to answer before the issue-fixed, I was going to stress on “this API is used when correctness — and ease to use correctly — is more important than speed, so the extra pointer doesn't seem a prohibitive cost”.

> (ii) change the other key-related member functions into free-standing algorithms

I specially liked this. Good idea.
