### ISSUE TITLE
dynamic::variable: rename number to real

### ISSUE THREAD

**Issue by breese** [breese/trial.protocol#17]
Floating-point numbers are current referred to as `symbol::number` (for comparison integer numbers use `symbol::integer`.)

I have never been pleased with that term, so I am planning to renaming it to `symbol::real`. This name fits well with the meaning of `std::real`.

This will be a (trivial) breaking-change for `dynamic::variable`, so I want to hear if there are any objections.

Likewise, I plan to rename `code::float_number`, `code::double_number`, and `code::long_double_number` to `code::short_real`, `code::real`, and `code::long_real` respectively.

**Comment by vinipsmaker** [comment]
> I want to hear if there are any objections

No objections for the first part.

About the second part, float, double and long double give the intention right at the first sight. Maybe they should be preserved (and the only change being `number -> real`).

**Comment by breese** [comment]
We could have aliases for the floating-point codes. E.g.

- float = `code:float_number` and `code:real`
- double = `code::double_number` and `code::long_real`
- long double = `code::long_double_number` and `code::long_long_real`

**Comment by vinipsmaker** [comment]
> We could have aliases for the floating-point codes.

But wouldn't aliases generate boring warnings on unhandled switch cases? Not sure I like this approach.

**Comment by vinipsmaker** [comment]
> But wouldn't aliases generate boring warnings on unhandled switch cases?

Nevermind. I've tested here and compilers are smart enough to handle such obivetes. 😅

I'm okay with your solution.

**Comment by breese** [comment]
Fixed in bcedbf443924beb581e9ad21f598bd6870f21f63
