### ISSUE TITLE
When is `json::token::symbol::separator` supposed to be emitted?

### ISSUE THREAD

**Issue by vinipsmaker2** [breese/trial.protocol#3]
I did several small tests and I don't get when this token could help me in my logic. It's never emitted in my tests (I didn't grep through the code to know where it's being used).

**Comment by breese** [comment]
The `separator` symbol is internal so the user will never see it. It is used in the interaction between `json::reader` and its internal lexer `json::detail::decoder`.

 I should probably hide it somehow from the public API.

**Comment by vinipsmaker2** [comment]
> I should probably hide it somehow from the public API.

Yes, you should.

**Comment by breese** [comment]
Fixed in e8af9fab9394d2758f8bac97523f0af4e3285023
