### ISSUE TITLE
What's the state of the feature/tree branch?

### ISSUE THREAD

**Issue by vinipsmaker** [breese/trial.protocol#32]

**Comment by breese** [comment]
Merged into develop back in March.

**Comment by vinipsmaker** [comment]
![screenshot_2018-12-09 breese trial protocol](https://user-images.githubusercontent.com/865914/49698582-ff3dff80-fbac-11e8-9e82-4e53c4daa7c0.png)

Sorry. I was misled by GitHub bars.
