### ISSUE TITLE
Split symbol::string and symbol::object_key events

### ISSUE THREAD

**Issue by vinipsmaker** [breese/trial.protocol#50]

**Comment by breese** [comment]
Added in 7ae343983f7d1b1b82938752fb762050f1bec74e

**Comment by vinipsmaker** [comment]
You missed one spot:

https://github.com/breese/trial.protocol/blob/7ae343983f7d1b1b82938752fb762050f1bec74e/include/trial/protocol/json/detail/reader.ipp#L360

By manually changing this line, I verified the commit 7ae343983f7d1b1b82938752fb762050f1bec74e works on my code base.

Anyway, that was quick. Many thanks.

**Comment by breese** [comment]
Good catch. Fixed in 6d01c6e3387c6efe2367d4698cd5ba8f31c1a3ef
