### ISSUE TITLE
Array and map construction

### ISSUE THREAD

**Issue by breese** [breese/trial.protocol#9]
On the feature/dynamic branch it is possible to construct a `dynamic::variable` by passing a `variable::array_type` (aka `std::vector<variable>`.) I want to change this to used named constructors instead.

For example, the following code:
```
std::vector<variable> values;
variable data(values);
```
should be changed into:
```
std::variable<variable> values;
variable data = variable::array(values.begin(), values.end());
```
The reason for this change is that the current code can lead to surprising results. While working on adding support for `operator<<` I encountered an infinite recursion because `operator<<(variable)` was invoked when given a `std::vector<variable>`.

I could have solved the recursion by adding an overload for `std::vector<variable>` but that would preclude users from adding their own. Notice that `operator<<(variable)` simply forwards to `operator<<` of the underlying type, so the default behaviour of `operator<<(std::vector<variable>)` should be a compiler error (unless a custom overload exists.) It is not used for serialization.

All of the above also applies to `variable::map_type`.

Any objections?

**Comment by vinipsmaker** [comment]
> Any objections?

Not from my side.
